name: flutter_firebase_auth
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.4
  firebase_database: ^6.1.2
  cupertino_icons: ^0.1.3
  firebase_auth: ^1.0.3
  google_fonts: ^2.0.0
  page_transition: ^1.1.5
  firebase_storage: ^8.0.3
  firebase_core: ^1.0.3
  permission_handler: ^6.1.1
  firebase_analytics: ^7.1.1
  geolocator: ^5.3.0
  location_permissions: ^3.0.0+1
  fluttertoast: ^8.0.3
  progress_dialog: ^1.2.4
  shared_preferences: ^2.0.5
  android_intent: ^2.0.0
  getwidget: ^1.2.4
  camera:
  path_provider:
  path:
  image_picker:
  image_cropper: ^1.3.1
  provider: ^4.1.2
  http: ^0.13.1
  intl: ^0.17.0
  geolocation: ^1.1.2
  flutter_image_compress: ^1.0.0
  fab_circular_menu: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

